updated workflow files

diff --git a/.github/workflows/test-model.yml b/.github/workflows/test-model.yml
--- a/.github/workflows/test-model.yml
+++ b/.github/workflows/test-model.yml
@@ -1,4 +1,4 @@
-name: Model Test on push
+name: Model test on push
 
 on:
   push: 
@@ -66,12 +66,30 @@ jobs:
           BRANCH: "main"
           REPO_NAME: ${{ github.event.repository.name }}
           AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 10
+          max_attempts: 3
+          command: |
+            source activate
+            pip install requests pyairtable
+            echo "Updating metadata to AirTable looking at owner: $USER_NAME"
+            wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/airtableops.py
+            python3 airtableops.py airtable-update --user $USER_NAME --repo $REPO_NAME --branch $BRANCH --api-key $AIRTABLE_API_KEY
+            rm airtableops.py
+
+      - name: sync metadata to S3 JSON
+        id: sync-metadata-to-s3
+        env:
+          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         run: |
           source activate
-          echo "Updating metadata to AirTable looking at owner: $USER_NAME"
-          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_metadata_to_airtable.py
-          python3 update_metadata_to_airtable.py $USER_NAME $REPO_NAME $BRANCH $AIRTABLE_API_KEY
-          rm update_metadata_to_airtable.py
+          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/convert_airtable_to_json.py
+          pip install boto3 requests pyairtable
+          python convert_airtable_to_json.py $AIRTABLE_API_KEY $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
+          rm convert_airtable_to_json.py
 
       - name: Update README file
         id: update-readme-file
@@ -80,9 +98,9 @@ jobs:
         run: |
           source activate
           echo "Updating README file with AirTable metadata for model: $MODEL_ID"
-          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/update_readme_from_airtable.py
-          python3 update_readme_from_airtable.py $MODEL_ID .
-          rm update_readme_from_airtable.py
+          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/airtableops.py
+          python3 airtableops.py readme-update --repo $MODEL_ID --path .
+          rm airtableops.py
           less README.md
 
       - name: Commit and push changes done to the README file
@@ -96,22 +114,42 @@ jobs:
           amend: true
           force: true
       
-      - name: Predict output
+      - name: Fetch model
         env:
           MODEL_ID: ${{ github.event.repository.name }}
         run: |
-          source activate
-          echo "Sample model id selected: $MODEL_ID"
-          ersilia -v fetch $MODEL_ID --repo_path .
-          ersilia -v serve $MODEL_ID
-          ersilia sample -n 5 -f input.csv
-          ersilia -v api -i input.csv
-          ersilia close
-          
+            source activate
+            ersilia -v fetch $MODEL_ID --from_dir .
+            FOLDER="$HOME/eos/repository/$MODEL_ID"
+            if [ ! -d "$FOLDER" ]; then
+              echo "Error: Folder '$FOLDER' does not exist." >&2
+              exit 1
+            fi
+
+      - name: Generate input and run model
+        env:
+          MODEL_ID: ${{ github.event.repository.name }}
+        run: |
+            source activate
+            ersilia -v serve $MODEL_ID
+            ersilia example inputs -n 5 -f input.csv --predefined
+            ersilia -v run -i "input.csv" -o "output.csv"
+            ersilia close
+            cat output.csv
+      
+      - name: Test output
+        run: |
+            output=$(python .github/scripts/verify_model_outcome.py output.csv)
+            if echo "$output" | grep -q "All outcomes are null"; then
+              echo "Error in model outcome, aborting test"
+              exit 1
+            fi
+            rm output.csv
+
       - name: Upload log output
+        if: always()
         uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #pin v3.1.1
         with:
           name: debug-logs
-          retention-days: 1
-          path: /home/runner/eos/console.log
-
+          retention-days: 14
+          path: /home/runner/eos/*.log
